### ISSUE TITLE
Footer does not stay at the bottom when zooming out

### ISSUE THREAD

**Issue by Pymon** [mlinke-ai/kev.in#153]

**Comment by aschadli** [comment]
I tried several things and came to the conclution, that we have two options:
- Eighter make the footer sticky -> you can see the footer even if you scrolled up but the footer stayes on bottom if you zoom out
- Or leave it as it is now -> you can see the footer only if scrolled down but the issue is not fixed

I looked at some websites (for example github) and they all implemented it as in the second case. I think nomaly this is not a problem because the page content is long enough. Maybe it is possible to implement some crazy JevaScript to fix the issue and leave the footer at the bottom of the page, but I don't know if that's appropriate.

**Comment by Pymon** [comment]
position: fixed;
left: 0;
bottom: 0;

**Comment by Pymon** [comment]
Ok we have bigger issues anyways right now
